version: "2"

services:

  outline-postgres:
    container_name: ${OTLINE_POSTGRES_CONTAINER_NAME}
    image: ${OTLINE_POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_USER: ${OTLINE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${OTLINE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${OTLINE_POSTGRES_DB}
      PGPORT: ${OTLINE_POSTGRES_PORT}
    networks:
      - backend
    volumes:
      - ./outline/postgres-data/db:/var/lib/postgresql/data:Z
    #ports:
    #  - "${OTLINE_POSTGRES_PORT}:5432"


  outline-redis:
    container_name: ${CONTAINER_NAME_REDIS}
    image: ${REDIS_VERSION}
    restart: always
    networks:
      - backend

  outline-minio:
    container_name: ${CONTAINER_NAME_MINIO}
    image: ${MINIO_VERSION}
    restart: always
    volumes:
      - ./outline/minio-data/data:/data:Z
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}
    # ports:
      # - ${MINIO_PORT}:9000
      # - ${MINIO_PORT_ADMIN}:9001
    networks:
      - reverseproxy
    command: "server /data --console-address :${MINIO_PORT_ADMIN}"

  outline:
    container_name: outline
    image: ${OUTLINE_VERSION}
    user: root
    restart: always
    command: sh -c "yarn db:migrate --env=production-ssl-disabled && yarn start --env=production-ssl-disabled"
    depends_on:
      - outline-postgres
      - outline-redis
      - outline-minio
    
    environment:
      - PGSSLMODE=disable
      - SECRET_KEY=${SECRET_KEY}
      - UTILS_SECRET=${UTILS_SECRET}
      - DATABASE_URL=postgres://${OTLINE_POSTGRES_USER}:${OTLINE_POSTGRES_PASSWORD}@${OTLINE_POSTGRES_CONTAINER_NAME}:${OTLINE_POSTGRES_PORT}/outline
      - REDIS_URL=redis://${CONTAINER_NAME_REDIS}:${REDIS_PORT}
      - URL=${WIKI_URL}
      - PORT=${OUTLINE_PORT}
      - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE}
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_S3_UPLOAD_BUCKET_URL=${WIKIDATA_MINIO_URL}
      - AWS_S3_UPLOAD_BUCKET_NAME=outline
      - AWS_S3_UPLOAD_MAX_SIZE=26214400
      - AWS_S3_FORCE_PATH_STYLE=true
      - AWS_S3_ACL=private
      # Авторизация, через OIDC
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_AUTH_URI=${OIDC_AUTH_URI}
      - OIDC_TOKEN_URI=${OIDC_TOKEN_URI}
      - OIDC_USERINFO_URI=${OIDC_USERINFO_URI}
            
      # При необходимости, можно сразу добавить авторизацию с помощью Slack:
      #- SLACK_CLIENT_ID=${SLACK_CLIENT_ID}
      #- SLACK_CLIENT_SECRET=${SLACK_CLIENT_SECRET}
      
      # При необходимости, можно сразу добавить авторизацию с помощью Google:
      #- GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      #- GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

    ports:
      - "${OUTLINE_PORT}:3000"
    networks:
      - backend
      - reverseproxy

networks:
  backend:
    name: outline-backend
  reverseproxy:
    external: true

